### PR TITLE
Adding 'Edit with VS Code' to main branch

### PR DESCRIPTION
**Pull request by Apprentice76**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [x] Extension 
- [ ] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Comment by jainaayush01** [comment]
Hey, @Apprentice76 kudos to your hard work, please go through the below notes:
1. It will be easy for us to review the pull request if you don't add the project as a submodule.
      To do so: 
      Fork this repo, 
      Clone to your local machine
      Add all files other than the .git folder

2. make sure you add folders like .vscode, .DS_Store which are not relevant on other machines in .gitignore and not add it the repo

3. Make sure to provide a readme.md file explaining the project as a whole

The deadline has been extended so feel free to add more features or changes to the extension and improve the code readability in any way possible.

Cheers,
Aayush

**Comment by jainaayush01** [comment]
You will have to make a new pull request for this work.
Feel free to add your thoughts and doubts if you have any in the comments or on slack.

close this pull request as of now.

**Comment by Apprentice76** [comment]
Ok, I'll remove it as submodule and create a new PR

**Review by jainaayush01 — CHANGES_REQUESTED** [review]
Hey, @Apprentice76 kudos to your hard work, please go through the below notes:

It will be easy for us to review the pull request if you don't add the project as a submodule.
To do so:
Fork this repo,
Clone to your local machine
Add all files other than the .git folder

make sure you add folders like .vscode, .DS_Store which are not relevant on other machines in .gitignore and not add it the repo

Make sure to provide a readme.md file explaining the project as a whole

The deadline has been extended so feel free to add more features or changes to the extension and improve the code readability in any way possible.

Cheers,
Aayush

**Comment by sudhanshutiwari264** [comment]
@Apprentice76  will have to make a new pull request for this work.
Closing this pull request!

waiting for your new pull request :partying_face:

**Pull request closed without merging**
