### PR TITLE
CareU - A Chrome Extension

### PR DESCRIPTION
**Pull request by nsachin08**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [x] Extension 

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Comment by Nitesh-thapliyal** [comment]
Nice work @nsachin08 
Here are some suggestions :

- Increase the time to display instruction of quotes
Screenshot (1161)

- Quotes are not changing after clicking on it
Screenshot (1160)

**Review by theAdityaNVS — APPROVED** [review]
Great All in One extension @nsachin08 !!
Also dark mode would be great.

**Review by jainaayush01 — APPROVED** [review]

**Comment by nsachin08** [comment]
> Nice work @nsachin08 
> Here are some suggestions :
> 
> - Increase the time to display instruction of quotes
> Screenshot (1161)
> 
> - Quotes are not changing after clicking on it
> Screenshot (1160)
> 

@Nitesh-thapliyal  Actually We dont have to click anywhere .I was thinking of other solution. But later came to a solution it will automatically load the quotes and replace the quote section element automatically  . I have to change the text and also there should be Internet connectivity to fetch the quote.

**Comment by nsachin08** [comment]
> Great All in One extension @nsachin08 !!
> Also dark mode would be great.

Thank You , Yes I will be adding that functionality too .

**Comment by Nitesh-thapliyal** [comment]
> > Nice work @nsachin08
> > Here are some suggestions :
> > 
> > * Increase the time to display instruction of quotes
> >   Screenshot (1161)
> > * Quotes are not changing after clicking on it
> >   Screenshot (1160)
> 
> @Nitesh-thapliyal Actually We dont have to click anywhere .I was thinking of other solution. But later came to a solution it will automatically load the quotes and replace the quote section element automatically . I have to change the text and also there should be Internet connectivity to fetch the quote.

Without clicking also quotes are not changing and change the instruction of quote

**Comment by nsachin08** [comment]
Ok I am looking into the issue.

**Comment by Nitesh-thapliyal** [comment]
> > > Nice work @nsachin08
> > > Here are some suggestions :
> > > 
> > > * Increase the time to display instruction of quotes
> > >   Screenshot (1161)
> > > * Quotes are not changing after clicking on it
> > >   Screenshot (1160)
> > 
> > 
> > @Nitesh-thapliyal Actually We dont have to click anywhere .I was thinking of other solution. But later came to a solution it will automatically load the quotes and replace the quote section element automatically . I have to change the text and also there should be Internet connectivity to fetch the quote.
> 
> Without clicking also quotes are not changing and change the instruction of quote

**Comment by nsachin08** [comment]
> > > Nice work @nsachin08
> > > Here are some suggestions :
> > > 
> > > * Increase the time to display instruction of quotes
> > >   Screenshot (1161)
> > > * Quotes are not changing after clicking on it
> > >   Screenshot (1160)
> > 
> > @Nitesh-thapliyal Actually We dont have to click anywhere .I was thinking of other solution. But later came to a solution it will automatically load the quotes and replace the quote section element automatically . I have to change the text and also there should be Internet connectivity to fetch the quote.
> 
> Without clicking also quotes are not changing and change the instruction of quote

Each time we open the Quote option in the extension . It will fetch only once . to generate next quote we have to click on the quote option(top left option) again. It will fetch only once per view.

**Comment by Nitesh-thapliyal** [comment]
> > > > Nice work @nsachin08
> > > > Here are some suggestions :
> > > > 
> > > > * Increase the time to display instruction of quotes
> > > >   Screenshot (1161)
> > > > * Quotes are not changing after clicking on it
> > > >   Screenshot (1160)
> > > 
> > > 
> > > @Nitesh-thapliyal Actually We dont have to click anywhere .I was thinking of other solution. But later came to a solution it will automatically load the quotes and replace the quote section element automatically . I have to change the text and also there should be Internet connectivity to fetch the quote.
> > 
> > 
> > Without clicking also quotes are not changing and change the instruction of quote
> 
> Each time we open the Quote option in the extension . It will fetch only once . to generate next quote we have to click on the quote option(top left option) again. It will fetch only once per view.

Can you add a feature like we don't have to click on the quote button again and again as it will be more convenient

**Comment by nsachin08** [comment]
> > > > > Nice work @nsachin08
> > > > > Here are some suggestions :
> > > > > 
> > > > > * Increase the time to display instruction of quotes
> > > > >   Screenshot (1161)
> > > > > * Quotes are not changing after clicking on it
> > > > >   Screenshot (1160)
> > > > 
> > > > 
> > > > @Nitesh-thapliyal Actually We dont have to click anywhere .I was thinking of other solution. But later came to a solution it will automatically load the quotes and replace the quote section element automatically . I have to change the text and also there should be Internet connectivity to fetch the quote.
> > > 
> > > 
> > > Without clicking also quotes are not changing and change the instruction of quote
> > 
> > Each time we open the Quote option in the extension . It will fetch only once . to generate next quote we have to click on the quote option(top left option) again. It will fetch only once per view.
> 
> Can you add a feature like we don't have to click on the quote button again and again as it will be more convenient 

Yes , Sure Great Idea.

**Review by SulthanNK — APPROVED** [review]
Hi @nsachin08 

Kudos to your work and My opinion is (It's great if you change the colour of the font too, sometimes it's hard to read if you add multiple tasks.

It's cool if you added the features @Nitesh-thapliyal and @theAdityaNVS requested.

Cheers from @SulthanNK

**Comment by archithdwij** [comment]
@nsachin08 This is solid work brother. Very well done! Congratulations on getting your PR Merged!

**Review by archithdwij — APPROVED** [review]

**Comment by archithdwij** [comment]
@all-contributors Please add @nsachin08 for code, idea, design, infra

**Pull request merged**
