### PR TITLE
Quick_Media_Launcher 

### PR DESCRIPTION
**Pull request by abbasrangwala111**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [x] Extension 
- [ ] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [ ]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Nice work @abbasrangwala111 
Can you make a readme good by using markdown,  take help of GitHub markdown [guide](https://guides.github.com/features/mastering-markdown/) 

By using markdown it will look clean and easier to read

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Great work extension is working smoothly

Here are some suggestions that you can work on: 

-  can you remove google from it as when I am on the browser, I can access google very easily for that extension is not needed, so remove it and instead add something else. 

- Add icons for the below social media buttons also like for google meet, zoom, team, all those buttons.

- Can you give users the capability to add the social accounts to the extension by themselves
 

Screenshot (1171)

**Comment by abbasrangwala111** [comment]
Sure. I will try to implement changes.

**Review by theAdityaNVS — CHANGES_REQUESTED** [review]
- Can you add a dark mode switch since its too white
- Also can you add some styling to the buttons, its looks a bit generic.

**Comment by jainaayush01** [comment]
@abbasrangwala111 Let us know when all requested changes are done
cheers

**Comment by Nitesh-thapliyal** [comment]
@abbasrangwala111  are all changes made ?

**Comment by abbasrangwala111** [comment]
I have made certain changes. Do check it out.

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
- Icons are not looking good as above, try to make them look same.
- create a folder in repo and upload all pics inside it
- can you add a feature that will help users to add social account in extension
Screenshot (1172)

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Looks like there is an error in the program
- dark theme function is not working I guess, fix this error

Screenshot (1173)

**Comment by abbasrangwala111** [comment]
@Nitesh-thapliyal The above icons are already inbuilt functions of html whereas the icons below are not available, so i have created image buttons.

**Review by Nitesh-thapliyal — COMMENTED** [review]
Do follow the chrome security policy, for details go through the [chrome security policy](https://developer.chrome.com/docs/apps/contentSecurityPolicy/#:~:text=The%20content%20security%20policy%20for,...%22%3E%20)

**Comment by Nitesh-thapliyal** [comment]
> @Nitesh-thapliyal The above icons are already inbuilt functions of html whereas the icons below are not available, so i have created image buttons.

you can apply CSS on them, to look good

**Comment by abbasrangwala111** [comment]
@Nitesh-thapliyal I will check the error.

**Comment by Nitesh-thapliyal** [comment]
> Do follow the chrome security policy, for details go through the [chrome security policy](https://developer.chrome.com/docs/apps/contentSecurityPolicy/#:~:text=The%20content%20security%20policy%20for,...%22%3E%20)

If they are inbuilt functions that means you can use them again

**Comment by Nitesh-thapliyal** [comment]
> @Nitesh-thapliyal The above icons are already inbuilt functions of html whereas the icons below are not available, so i have created image buttons.

If they are inbuilt functions that means you can use them again

**Comment by abbasrangwala111** [comment]
Can anyone help me with the dark mode error it works fine on the local machine whereas it shows an error in extension.

**Comment by jainaayush01** [comment]
Can u share the screenshots of both?

**Comment by abbasrangwala111** [comment]
@jainaayush01

**Comment by abbasrangwala111** [comment]
@jainaayush01 [chrome://extensions/?errors=gjeebkdgllfdpikdmciofiojfahkpgif](url)

**Comment by abbasrangwala111** [comment]
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem:". Either the 'unsafe-inline' keyword, a hash ('sha256-tUJxy3ThHBsgVqSO6qALZ8wS2/4tFt3I3rsC5uFxmNw='), or a nonce ('nonce-...') is required to enable inline execution.

This is the error

**Comment by Nitesh-thapliyal** [comment]
> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem:". Either the 'unsafe-inline' keyword, a hash ('sha256-tUJxy3ThHBsgVqSO6qALZ8wS2/4tFt3I3rsC5uFxmNw='), or a nonce ('nonce-...') is required to enable inline execution.
> 
> This is the error

I have shared a content security policy with you in the above comments, go through it

**Comment by abbasrangwala111** [comment]
@Nitesh-thapliyal Thank you for sharing CSP

**Comment by abbasrangwala111** [comment]
I have committed changes and the dark mode button now works.

**Comment by sudhanshutiwari264** [comment]
You are doing a great job, @abbasrangwala111, but 
Two changes are requested: 
- We need exact buttons as in the image above (you can use Canva or any other app to do this). 
- Add a feature that will allow users to add social media accounts to the extension

Please do not hesitate to contact me if you need assistance.

**Review by sudhanshutiwari264 — CHANGES_REQUESTED** [review]
You are doing a great job, @abbasrangwala111, but
Two changes are requested:

- We need exact buttons as in the image above (you can use Canva or any other app to do this).
- Add a feature that will allow users to add social media accounts to the extension

Please do not hesitate to contact me if you need assistance.

**Comment by abbasrangwala111** [comment]
I have changed the icons, I will add a detailed explanation in readme.md file for the user to change or add social media links in the HTML file manually. @sudhanshutiwari264

**Review by jainaayush01 — APPROVED** [review]
LGTM.

**Review by archithdwij — APPROVED** [review]

**Review by sudhanshutiwari264 — APPROVED** [review]
@abbasrangwala111 Thank you for your dedication!

**Comment by archithdwij** [comment]
@all-contributors Please add @abbasrangwala111 for code, infra, design

**Pull request merged**
