### PR TITLE
Fylfot-Chrome Extension

### PR DESCRIPTION
**Pull request by AKG1301**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [x] Extension 
- [ ] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Comment by Nitesh-thapliyal** [comment]
Hey @AKG1301 nice work👏
Here are suggestions that you can work on: 
- Remove the thought section from the full screen as it can be added in the extension itself
- Todo list is already present in the market and in the competition also many participants have made Todo list, so add some feature that will stand out your todo list and make it more productive
- Text to speech is not productive I guess as we need to add text  manually,  can you add a feature to it like user can select the text and then it will read it out  that you can do but for this also extension is available

So analyze the other similar extensions, check their functionality, and make your extension more productive

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Hey @AKG1301 nice work👏
Here are suggestions that you can work on:

- Remove the thought section from the full screen as it can be added in the extension itself
- Todo list is already present in the market and in the competition also many participants have made Todo list, so add some feature that will stand out your todo list and make it more productive
- Text to speech is not productive I guess as we need to add text manually, can you add a feature to it like user can select the text and then it will read it out that you can do but for this also extension is available

So analyze the other similar extensions, check their functionality, and make your extension more productive

And after some time extension is giving the following error
Screenshot (1211)

**Comment by AKG1301** [comment]
>* "Remove the thought section from the full screen as it can be added in the extension itself"
Thank you for marking it out. The main purpose of implementing the Random thought Section on the click of the new Tab was to inspire the user because most of the time. a user usually does not prefer to click on the Thought option on their own. So, It will be great, a thought appears on their screen automatically. on an additional note if I implement the thought section in the extension itself it will acquire some space.
>* "Todo list"
Todo list is the feature that I have added for ease of work.
>* "Text to Speech"
In this feature, we don't have to add text manually every time a user can simply click on the text and then click on the extension option, it will work perfectly as I have demonstrated in the video. the error you have attached comes only when you click on the 'speak' option without Selecting the text, in that particular scenario, It will generate an error.

**Comment by Nitesh-thapliyal** [comment]
> > * "Remove the thought section from the full screen as it can be added in the extension itself"
> >   Thank you for marking it out. The main purpose of implementing the Random thought Section on the click of the new Tab was to inspire the user because most of the time. a user usually does not prefer to click on the Thought option on their own. So, It will be great, a thought appears on their screen automatically. on an additional note if I implement the thought section in the extension itself it will acquire some space.
> > * "Todo list"
> >   Todo list is the feature that I have added for ease of work.
> > * "Text to Speech"
> >   In this feature, we don't have to add text manually every time a user can simply click on the text and then click on the extension option, it will work perfectly as I have demonstrated in the video. the error you have attached comes only when you click on the 'speak' option without Selecting the text, in that particular scenario, It will generate an error.



> > * "Remove the thought section from the full screen as it can be added in the extension itself"
> >   Thank you for marking it out. The main purpose of implementing the Random thought Section on the click of the new Tab was to inspire the user because most of the time. a user usually does not prefer to click on the Thought option on their own. So, It will be great, a thought appears on their screen automatically. on an additional note if I implement the thought section in the extension itself it will acquire some space.
> > * "Todo list"
> >   Todo list is the feature that I have added for ease of work.
> > * "Text to Speech"
> >   In this feature, we don't have to add text manually every time a user can simply click on the text and then click on the extension option, it will work perfectly as I have demonstrated in the video. the error you have attached comes only when you click on the 'speak' option without Selecting the text, in that particular scenario, It will generate an error.

- As per the theme WFH remote productivity tool, thoughts on full screen are decreasing productivity as there are chrome shortcuts available in the screen which are hidden due to full screen thoughts.
- And todo list is already made by many participants and there are many extension already available for todo, so can you add extra feature that will make your extension stand out from other and more productive. Here are the some of todo extensions go through them and analyze the feature, functionality and try to make your extension more productive. 
 ToDo Extensions: 
 - [Todoist](https://chrome.google.com/webstore/detail/todoist-for-chrome/jldhpllghnbhlbpcmnajkpdmadaolakh?hl=en)
 - [any.do](https://www.any.do/to-do-list-app-for-chrome/)
 
 And for the text to speech feature, here is a suggestion: 
 - make it productive by adding a feature like when user click on the text it read it out for them instead of opening extension again and again. Here is list of text to speech extensions go through them and then try to make your extension more productive. [Text to speech](https://www.thestartupfounder.com/top-5-text-to-speech-chrome-extensions-alternatives-for-capti-voice/)

**Review by jainaayush01 — APPROVED** [review]
LGTM

**Review by Nitesh-thapliyal — APPROVED** [review]

**Review by sudhanshutiwari264 — APPROVED** [review]
LGTM

**Review by SulthanNK — APPROVED** [review]
LGTM

**Review by archithdwij — APPROVED** [review]
@AKG1301 I like how you have packed the UI with the features. However, the features themselves are already present at the market in an extensive manner. We are gonna go ahead and merge your PR and rate your project accordingly. Congratulations!

**Comment by archithdwij** [comment]
@all-contributors Kindly add @AKG1301 for infra, code, design

**Pull request merged**
