### PR TITLE
Ayush78781/chrome extension/add

### PR DESCRIPTION
**Pull request by ayush78781**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [x] Extension 
- [ ] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Hey @ayush78781 nice work👏
but your extension is not working, as I am entering the item in todo list instead of showing it in the output it is returning null, so can you look into this and fix it asap and add a readme to your repo.

Screenshot (1218)

**Note -  Make changes before evening so that we can merge it**

**Comment by ayush78781** [comment]
Ok @Nitesh-thapliyal will fix it by evening. Will add readme too. Thanks for reviewing.

**Comment by jainaayush01** [comment]
are all the changes done @ayush78781 ?

**Comment by ayush78781** [comment]
Yeah! It's almost done I will update it by today evening. I wasn't able to do it yesterday because I had my exam.

**Review by archithdwij — APPROVED** [review]

**Comment by archithdwij** [comment]
@ayush78781 let us know once its done so that we can proceed

**Comment by ayush78781** [comment]
Hey! @Nitesh-thapliyal its done with all fixes. The new thing I have added here is converted it into a Note-Taking Extension instead of a To-do list. As we are told not to make a to-do list. Also, added readme file to enhance the understanding of the code base. Please take a review.

**Review by Nitesh-thapliyal — APPROVED** [review]
Nice work @ayush78781 👏

**Comment by archithdwij** [comment]
@ayush78781 Congratulations on getting your PR merged!

**Comment by archithdwij** [comment]
@all-contributors Please add @ayush78781 for code, infra, design, idea

**Comment by ayush78781** [comment]
> @ayush78781 Congratulations on getting your PR merged!

Thankyou so much 🎉🎉. It really mean me a lot🥳🥳

**Pull request merged**
