### PR TITLE
Added Snippets saving, editing and deletion features. Also added Git-Cloner

### PR DESCRIPTION
**Pull request by Apprentice76**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [x] Extension 
- [ ] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Comment by Apprentice76** [comment]
I'll update Readme in the morning with more Gifs, making a PR beforehand for reviewing & testing.

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Hey @Apprentice76 nice work 👏
I tried your extension and the clone git input box is not working and can you align the snippet box in the center of the screen.
and due to unknown reasons, the editor is not opening when I am trying to open text in the editor
Screenshot (1189)

And when trying to open text using Quick edit then the editor is not opening but in snippet extra snippet box is created so can you make the changes like new text should be added to the present snippet box rather than creating a new box again and again
Screenshot (1190)

**Comment by Apprentice76** [comment]
In the input box you need to enter the folder path in you pc where you want to clone it. 

> I tried your extension and the clone git input box is not working

**Comment by Nitesh-thapliyal** [comment]
> In the input box you need to enter the folder path in you pc where you want to clone it.
> 
> > I tried your extension and the clone git input box is not working

Updated the comment

**Comment by Apprentice76** [comment]
> And when trying to open text using Quick edit then the editor is not opening but in snippet extra snippet box is created so can you make the changes like new text should be added to the present snippet box rather than creating a new box again and again
> Screenshot (1190)

Have you tried refreshing the page and then trying to copy and see if editor opens? 
As for snippets, if I go on adding snippets to same box, wouldn't that result in one gigantic text file, hence per snippet I've assigned their own card.

**Comment by Nitesh-thapliyal** [comment]
> > And when trying to open text using Quick edit then the editor is not opening but in snippet extra snippet box is created so can you make the changes like new text should be added to the present snippet box rather than creating a new box again and again
> > Screenshot (1190)
> 
> Have you tried refreshing the page and then trying to copy and see if editor opens?
> As for snippets, if I go on adding snippets to same box, wouldn't that result in one gigantic text file, hence per snippet I've assigned their own card.

And what I want to edit a large file how many boxes will be created in a window so try to make it a single box and add a scroll bar to it

**Comment by Apprentice76** [comment]
I see Notepad is selected, actually windows starts notepad in the background for some reason. Can you check if its one of your windows in your desktop?

**Comment by Nitesh-thapliyal** [comment]
And in input box we need to enter the path where we want to clone repo but where to specify which repo to clone?

**Comment by Apprentice76** [comment]
> > > And when trying to open text using Quick edit then the editor is not opening but in snippet extra snippet box is created so can you make the changes like new text should be added to the present snippet box rather than creating a new box again and again
> > > Screenshot (1190)
> > 
> > 
> > Have you tried refreshing the page and then trying to copy and see if editor opens?
> > As for snippets, if I go on adding snippets to same box, wouldn't that result in one gigantic text file, hence per snippet I've assigned their own card.
> 
> And what I want to edit a large file how many boxes will be created in a window so try to make it a single box and add a scroll bar to it

Ok I'll check.

**Comment by Nitesh-thapliyal** [comment]
> I see Notepad is selected, actually windows starts notepad in the background for some reason. Can you check if its one of your windows in your desktop?

checked nothing is opening for me

**Comment by Apprentice76** [comment]
> And in input box we need to enter the path where we want to clone repo but where to specify which repo to clone?

when you go to a github repo, there is a Green Code box, Clicking it there is a clipboard button. This extension overrides it. When you click the clipboard button, it will be cloned in given directory.

**Comment by Apprentice76** [comment]
> > I see Notepad is selected, actually windows starts notepad in the background for some reason. Can you check if its one of your windows in your desktop?
> 
> checked nothing is opening for me

That shouldn't happen...I haven't changed that functionality, try copying the extension ID and running install.bat again

**Comment by Nitesh-thapliyal** [comment]
> > And in input box we need to enter the path where we want to clone repo but where to specify which repo to clone?
> 
> when you go to a github repo, there is a Green Code box, Clicking it there is a clipboard button. This extension overrides it. When you click the clipboard button, it will be cloned in given directory.

I did as the steps are mentioned in readme but it is not working

**Comment by Nitesh-thapliyal** [comment]
> > > I see Notepad is selected, actually windows starts notepad in the background for some reason. Can you check if its one of your windows in your desktop?
> > 
> > 
> > checked nothing is opening for me
> 
> That shouldn't happen...I haven't changed that functionality, try copying the extension ID and running install.bat again

did that couple of times but not working and there seems to be limit of text that snippet can hold I guess and certain world length it not taking any more text in snippet

**Comment by Nitesh-thapliyal** [comment]
and can you update the demo video with the git part also

**Comment by Apprentice76** [comment]
Yes doing that only, I'm installing everything from scratch, when video is uploaded, I'll share it here too.

**Comment by archithdwij** [comment]
@Apprentice76 A gentle reminder to submit your blog and updated video into the submission forms too after completing the feature additions. Cool?

**Comment by Apprentice76** [comment]
> @Apprentice76 A gentle reminder to submit your blog and updated video into the submission forms too after completing the feature additions. Cool?

Blog submission's by 11th right?

**Comment by archithdwij** [comment]
> > @Apprentice76 A gentle reminder to submit your blog and updated video into the submission forms too after completing the feature additions. Cool?
> 
> Blog submission's by 11th right?

Yes it is.

**Comment by Apprentice76** [comment]
> https://vimeo.com/573019919

@Nitesh-thapliyal  can you watch this?

**Comment by Nitesh-thapliyal** [comment]
Hey @Apprentice76 still there is snippet box issue, now only three boxes are created and there is limited text storing in a snippets

**Comment by Apprentice76** [comment]
> Hey @Apprentice76 still there is snippet box issue, now only three boxes are created and there is limited text storing in a snippets

🤔 This isn't happening in my side, have you tried refreshing the SNIPPET tab, it doesn't refresh automatically after getting new content.

**Comment by Apprentice76** [comment]
image

I'm also not seeing any limitation in content size.

**Comment by Nitesh-thapliyal** [comment]
> image
> 
> I'm also not seeing any limitation in content size.

Yes now it works great work👏

**Review by Nitesh-thapliyal — APPROVED** [review]

**Comment by archithdwij** [comment]
Good work @Apprentice76 Merging the PR 👍

**Review by jainaayush01 — COMMENTED** [review]
Great work, Kudos to you!
An innovative project and awesome dedication to the project.

**Comment by Apprentice76** [comment]
Thank you, this was a great learning experience for me, being my first extension and also I hadn't used this much vanilla JS before. In the beginning, the extension was doing a minimal task of opening VS Code via chrome and piping clipboard data to it, but thanks to all the reviewers' excellent feedback (especially @jainaayush01 and @Nitesh-thapliyal), this became far more. One of notable ones being editing in browser only without opening any editor and saving data in storage.

**Comment by sudhanshutiwari264** [comment]
@Apprentice76 great work 
👀 On this project from beginning and it's fantastic  !
We are happy to hear that , 🙈

**Pull request merged**
