### PR TITLE
manishdasa100/true note/add

### PR DESCRIPTION
**Pull request by manishdasa100**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [ x] Extension 
- [ ] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x ] Added readme.md to my project folder with relevant information.
- [ x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [ x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x ] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Hey @manishdasa100 nice work👏
but your extension is not working, it is showing the error mentioned below 

Screenshot (1219)

Here are some suggestions:
- add how to use the extension in the readme 
- Explain the project in the video

**Note: Make changes before evening so that we can merge it**

**Comment by manishdasa100** [comment]
Thanks Nitesh.
I have uploaded a new demo video explaining the working of the chrome extension. I have provided the new link in the README. 

Also as you have mentioned, if any error shows up on the extensions page, actually there is nothing to worry much. Chrome extensions tend to throw some weird errors while reading from the local storage. If something such happens then you can reload the extension and keep on using it happily.

**Comment by Nitesh-thapliyal** [comment]
> Thanks Nitesh.
> I have uploaded a new demo video explaining the working of the chrome extension. I have provided the new link in the README.
> 
> Also as you have mentioned, if any error shows up on the extensions page, actually there is nothing to worry much. Chrome extensions tend to throw some weird errors while reading from the local storage. If something such happens then you can reload the extension and keep on using it happily.

Great Work👏

**Review by Nitesh-thapliyal — APPROVED** [review]

**Review by sudhanshutiwari264 — APPROVED** [review]
Nice work @manishdasa100 🎉🥳

**Review by archithdwij — APPROVED** [review]

**Comment by sudhanshutiwari264** [comment]
@all-contributors Please add @manishdasa100  for code, design, infra

**Pull request merged**
