### PR TITLE
NotesTaker By Ravit

### PR DESCRIPTION
**Pull request by ravit27**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [x] Extension 
- [ ] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Review by Nitesh-thapliyal — COMMENTED** [review]
Great work @ravit27 👏
I tried your extension and it is working great⭐

Here is a suggestion that you can work on: 
- Can you add a feature so that users can delete a portion of text in the note taker extension, for example here if the user want to delete the selected text by pressing backspace. It will  be helpful user don't have to delete the whole text instead he can trim text in the notetaker extension  and it will save time, not to search for that portion of text again in the website

Screenshot (1175)

**Comment by ravit27** [comment]
Notes manipulation can be done in a downloaded word file.
If I add that feature here then in one scenario, If user deletes extra text by mistake in a extension ,then the note will be deleted and can't be reverted back. In such case this feature will become a con of this extension.

**Comment by Nitesh-thapliyal** [comment]
> Notes manipulation can be done in a downloaded word file.
> If I add that feature here then in one scenario, If user deletes extra text by mistake in a extension ,then the note will be deleted and can't be reverted back. In such case this feature will become a con of this extension.

make sense, btw nice work ⭐

Can you put all images in one folder in your repo

**Comment by ravit27** [comment]
Sure

**Comment by ravit27** [comment]
Done

**Review by Nitesh-thapliyal — APPROVED** [review]

**Review by sudhanshutiwari264 — APPROVED** [review]
Great work @ravit27 ! :partying_face: 
I plan to use them for personal use, @ravit27!

**Review by SulthanNK — APPROVED** [review]

**Review by archithdwij — APPROVED** [review]
@ravit27 Great work! Simple but effective tool. Congratulations on getting your PR merged!

**Comment by archithdwij** [comment]
@all-contributors Please add @ravit27 for code, idea, infra, design

**Pull request merged**
