### PR TITLE
To-Do Extension

### PR DESCRIPTION
**Pull request by BhavikSojitra**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [x] Extension 
- [ ] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of an application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you receive communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provided here. All the best :)

### CODE REVIEW

**Comment by BhavikSojitra** [comment]
To-Do Extension

**Review by theAdityaNVS — CHANGES_REQUESTED** [review]
Already we have lot of todo list in market.
Add some functions to make it unique.
- Add date function (when todo added or to be completed)
- Etc 
-

**Comment by jainaayush01** [comment]
Hey @BhavikSojitra , I can see that there are many to-do list chrome extensions.

We are sorry to say that we are not moving forward with this PR as the deadline is over

**Review by jainaayush01 — CHANGES_REQUESTED** [review]
Hey @BhavikSojitra , I can see that there are many to-do list chrome extensions.

We are sorry to say that we are not moving forward with this PR as the deadline is over

**Comment by BhavikSojitra** [comment]
I have already submitted my project two days from the deadline so there is nothing no issue with the deadline.

**Pull request closed without merging**
