### PR TITLE
PR#1  Word Nest 

### PR DESCRIPTION
**Pull request by MalayGain**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [x] Extension 
- [ ] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Hey @MalayGain nice work👏
but dictionary extensions are already available like google dictionary extension, so can you add some extra features that will stand it out from other dictionary extensions. Here is the list of the extension that are already present, go through them and see the features that they provide and analyze features that you can add that will make your extension more productive. [Dictonay Extensions](https://www.guidingtech.com/best-dictionary-extensions-chrome/)

**Review by theAdityaNVS — CHANGES_REQUESTED** [review]
As mentioned above,
Make changes such give source link of text and other functions to make your extension unique

**Comment by MalayGain** [comment]
I have added voice support feature which describes about the selected word and also detects if more than a single word is selected and gives response accordingly .This way, I find it is different from the list of the extension that are already present .Though I will try to make it more productive by time, any suggestions are always welcome .

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Hey @MalayGain extension is not working it is showing the following error, can you fix this
Screenshot (1212)

**Comment by MalayGain** [comment]
@Nitesh-thapliyal , really sorry my mistake . I forgot to import the library in the html file for popup . Hope it will fix the error

**Comment by Nitesh-thapliyal** [comment]
> @Nitesh-thapliyal , really sorry my mistake . I forgot to import the library in the html file for popup . Hope it will fix the error

No worries, btw good work👏 and do add about the voice feature in the readme.

**Review by Nitesh-thapliyal — APPROVED** [review]

**Review by sudhanshutiwari264 — APPROVED** [review]
Nice work @MalayGain 🎉

**Review by jainaayush01 — APPROVED** [review]

**Comment by sudhanshutiwari264** [comment]
@all-contributors Please add @MalayGain  for code, idea, design, infra.

**Comment by jainaayush01** [comment]
Congratulations @MalayGain for getting your PR merged 🥳

**Review by SulthanNK — COMMENTED** [review]
Kudo's to your work @MalayGain 🎉

**Pull request merged**
