### PR TITLE
WFHTool - Chrome Extension

### PR DESCRIPTION
**Pull request by kavya466**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [x ] Extension 
- [ ] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x ] Added readme.md to my project folder with relevant information.
- [x ]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x ] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x ] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Review by Nitesh-thapliyal — COMMENTED** [review]
Hey @kavya466 extension looks amazing⭐

But when I tried your extension it gave me an error as shown below👇
and it did not redirect me to file explorer to select manifest.json, am I missing something do let me know 

Screenshot (1184)

**Review by SulthanNK — COMMENTED** [review]
Hi @kavya466, The extension works well for me 🎉

But, I noticed an issue in prioritizing tasks. when I try to move the task, Instead of moving it's copying the task to another section. So, take a look at that.

wfh-tool-issue

UI Suggestion: It is better if you align those components like having equal space between everything, clock in the corner with date also,

**Comment by kavya466** [comment]
> Hey @kavya466 extension looks amazing⭐
> 
> But when I tried your extension it gave me an error as shown below👇
> and it did not redirect me to file explorer to select manifest.json, am I missing something do let me know
> 
> Screenshot (1184)

Can you please try going into src folder of my project while selecting the path

**Comment by kavya466** [comment]
> Hi @kavya466, The extension works well for me 🎉
> 
> But, I noticed an issue in prioritizing tasks. when I try to move the task, Instead of moving it's copying the task to another section. So, take a look at that.
> 
> wfh-tool-issue
> 
> UI Suggestion: It is better if you align those components like having equal space between everything, clock in the corner with date also,

Thanks for the review . Will try to do that

**Comment by Nitesh-thapliyal** [comment]
> > Hey @kavya466 extension looks amazing⭐
> > But when I tried your extension it gave me an error as shown below👇
> > and it did not redirect me to file explorer to select manifest.json, am I missing something do let me know
> > Screenshot (1184)
> 
> Can you please try going into src folder of my project while selecting the path

I am not getting option to select path, when I load package in chrome extension directly it is showing this error and when I am selecting src as a folder to load extension then it is showing only Todo feature

**Comment by kavya466** [comment]
> > > Hey @kavya466 extension looks amazing⭐
> > > But when I tried your extension it gave me an error as shown below👇
> > > and it did not redirect me to file explorer to select manifest.json, am I missing something do let me know
> > > Screenshot (1184)
> > 
> > 
> > Can you please try going into src folder of my project while selecting the path
> 
> I am not getting option to select path, when I load package in chrome extension directly it is showing this error and when I am selecting src as a folder to load extension then it is showing only Todo feature

Can you please share me the screenshot. Usually the window bar should show only the todo list and when you open the new tab, other components will be displayed

**Comment by Nitesh-thapliyal** [comment]
> > > > Hey @kavya466 extension looks amazing⭐
> > > > But when I tried your extension it gave me an error as shown below👇
> > > > and it did not redirect me to file explorer to select manifest.json, am I missing something do let me know
> > > > Screenshot (1184)
> > > 
> > > 
> > > Can you please try going into src folder of my project while selecting the path
> > 
> > 
> > I am not getting option to select path, when I load package in chrome extension directly it is showing this error and when I am selecting src as a folder to load extension then it is showing only Todo feature
> 
> Can you please share me the screenshot. Usually the window bar should show only the todo list and when you open the new tab, other components will be displayed

Ok got it , I did not open the new tab, now it works fine, do mention it in readme to select src folder to load extension and newtab one for full extension functionality

**Comment by kavya466** [comment]
> > > > > Hey @kavya466 extension looks amazing⭐
> > > > > But when I tried your extension it gave me an error as shown below👇
> > > > > and it did not redirect me to file explorer to select manifest.json, am I missing something do let me know
> > > > > Screenshot (1184)
> > > > 
> > > > 
> > > > Can you please try going into src folder of my project while selecting the path
> > > 
> > > 
> > > I am not getting option to select path, when I load package in chrome extension directly it is showing this error and when I am selecting src as a folder to load extension then it is showing only Todo feature
> > 
> > 
> > Can you please share me the screenshot. Usually the window bar should show only the todo list and when you open the new tab, other components will be displayed
> 
> Ok got it , I did not open the new tab, now it works fine, do mention it in readme to select src folder to load extension and newtab one for full extension functionality

Thanks for the update . I think i have mentioned that in readme file already, 3,4 points in installation section of it.

**Comment by Nitesh-thapliyal** [comment]
Great work @kavya466 👏 and same suggestion as Sulthan mentioned above

**Comment by kavya466** [comment]
> Great work @kavya466 👏 and same suggestion as Sulthan mentioned above

Thanks for the review nitesh. Will work on the updates suggested

**Review by sudhanshutiwari264 — COMMENTED** [review]
@kavya466 Great work! This is going to be a great productivity booster.
:partying_face: 
@Nitesh-thapliyal and @SulthanNK requested a number of changes - I hope you are working on them! :+1:

**Comment by kavya466** [comment]
> @kavya466 Great work! This is going to be a great productivity booster.
> 🥳
> @Nitesh-thapliyal and @SulthanNK requested a number of changes - I hope you are working on them! 👍

Thanks sudhan. Yes, i am working on the updates

**Comment by kavya466** [comment]
The changes suggested are updated. Can anyone please review?

**Comment by archithdwij** [comment]
@kavya466 I really love your work here. I have a doubt here. How does that quadrant work? I am not able to add data into that.

**Comment by kavya466** [comment]
> @kavya466 I really love your work here. I have a doubt here. How does that quadrant work? I am not able to add data into that.

Thanks @archithdwij . The idea of quadrant is to prioritize the the elements present in todos list. Drag a item from todo list and drop it in the empty area of grid. Dropping on the text will not have effect on moving the items. Please let me know if the issue still persists.

**Comment by archithdwij** [comment]
Oh Alright! That works fine. Thank you for updating the readme regarding the manifest path too. I am just curious here. Can we update the feature such that when we complete a task either in todo or quadrant, it should strike/go down the list of tasks or something like that?

**Comment by Nitesh-thapliyal** [comment]
> The changes suggested are updated. Can anyone please review?

Hey kavya, seems the alignment is still the same, can you make them all align at the same height, and can you make the time display at the right bottom
Screenshot (1191)

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Nice work @kavya466 
here is a suggestion then you are good to go : 

- Can you make alignment from both the end even like there is extra space from the left side of  the quadrant. todo list should come in the center of the screen 
Screenshot (1192)

**Comment by kavya466** [comment]
> Nice work @kavya466
> here is a suggestion then you are good to go :
> 
> * Can you make alignment from both the end even like there is extra space from the left side of  the quadrant. todo list should come in the center of the screen
>   Screenshot (1192)

Hi nitesh. Can you please let me know the resolution of the screen you have tested on.

**Comment by Nitesh-thapliyal** [comment]
> > Nice work @kavya466
> > here is a suggestion then you are good to go :
> > 
> > * Can you make alignment from both the end even like there is extra space from the left side of  the quadrant. todo list should come in the center of the screen
> >   Screenshot (1192)
> 
> Hi nitesh. Can you please let me know the resolution of the screen you have tested on.

1920 x 1080

**Comment by archithdwij** [comment]
@kavya466 We see the hard work you have put on to add all the suggested changes. We are gonna go ahead and merge your PR. But, we recommend that you do that alignment changes whenever possible. Congratulations 🎆

**Review by archithdwij — APPROVED** [review]

**Review by sudhanshutiwari264 — APPROVED** [review]
LGTM :+1: 
great work @kavya466 !

**Comment by archithdwij** [comment]
@all-contributors Please add @kavya466 for code, idea, design, infra

**Comment by Nitesh-thapliyal** [comment]
great work @kavya466 ⭐

**Comment by kavya466** [comment]
Thank you all for accepting the pull request. Its been a great learning experience!

**Review by jainaayush01 — COMMENTED** [review]
Congratulations @kavya466  for getting your PR merged 🥳

**Review by SulthanNK — COMMENTED** [review]
Congrats @kavya466 for getting your PR merged 🎉

**Pull request merged**
