### PR TITLE
Prodist PR

### PR DESCRIPTION
**Pull request by kichloo**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [x] Extension 
- [ ] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Review by sudhanshutiwari264 — CHANGES_REQUESTED** [review]
Hi @kichloo!
great project :+1: but ,
- I tried to test it, but it cannot locate the manifest file and there is no src file!
  Even after trying every single directory inside your project, the problem hasn't been solved!
- It would be great if a user could select which sites to block instead of blocking every single one of them!

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Hey @kichloo nice work👏
But there are many site blockers available, and you have hardcoded websites that can be blocked like Quora, Facebook, Instagram and Twitter. Can you add extra features that make it more productive

**Comment by jainaayush01** [comment]
> Hey @kichloo nice work👏
> But there are many site blockers available, and you have hardcoded websites that can be blocked like Quora, Facebook, Instagram, and Twitter. Can you add extra features that make it more productive?

Still, there are tools which will do that for us? can you come up with something not there in those [extensions](https://chrome.google.com/webstore/detail/blocksite-stay-focused-co/eiimnmioipafcokbfikbljfdeojpcgbh)?

**Comment by kichloo** [comment]
> Hi @kichloo!
> great project 👍 but ,
> 
> * I tried to test it, but it cannot locate the manifest file and there is no src file!
>   Even after trying every single directory inside your project, the problem hasn't been solved!
> * It would be great if a user could select which sites to block instead of blocking every single one of them!

By src, I was referring to the source (`Extension file`). Pl select that and then let me know it works or not. And can the other people see the extension?

**Comment by kichloo** [comment]
Regarding the other functionality, I would have to research on that because I am new to this domain

**Comment by sudhanshutiwari264** [comment]
> > Hi @kichloo!
> > great project +1 but ,
> > 
> > * I tried to test it, but it cannot locate the manifest file and there is no src file!
> >   Even after trying every single directory inside your project, the problem hasn't been solved!
> > * It would be great if a user could select which sites to block instead of blocking every single one of them!
> 
> By src, I was referring to the source file(`Extension file`). Pl select that and then let me know it works or not. And can the other people see the extension?

@kichloo 
I attempted to open the extension files at first, but that didn't unload, so I had to look at other folders in the project

**Comment by kichloo** [comment]
> @kichloo
> I attempted to open the extension files at first, but that didn't unload, so I had to look at other folders in the project

It's working fine in my system, don't know what's the problem in this case

**Comment by sudhanshutiwari264** [comment]
> It's working fine in my system, don't know what's the problem in this case

had you used .gitnore type while uploading the files ?

**Comment by kichloo** [comment]
> had you used .gitnore type while uploading the files ?

I had used Github for making the PR (did not use Git) and had uploaded the files in that case

**Comment by sudhanshutiwari264** [comment]
> > had you used .gitnore type while uploading the files ?
> 
> I had used Github for making the PR (did not use Git) and had uploaded the files in that case

No problem you work on the requested changes we will let you know if this problem persists!

**Comment by kichloo** [comment]
> No problem you work on the requested changes we will let you know if this problem persists!

Yeah, it will take some time and I would try to extend the functionality

**Review by SulthanNK — COMMENTED** [review]
Hi @kichloo, Nice work 🎉 

When I tried the extension, Twitter behaves differently Instead of blocking the page. So, Check this one also!

prodist-issue 

also, @sudhanshutiwari264 and @Nitesh-thapliyal requested some changes, hope you working on it.

**Comment by kichloo** [comment]
> When I tried the extension, Twitter behaves differently Instead of blocking the page. So, Check this one also!

@SulthanNK Yes, I had encountered that problem with Twitter many times! The system needs to be restarted in case of Twitter to see the changes on that site, don't know the reason behind that though

**Comment by kichloo** [comment]
I have added the extended functionality of timer in the blocker(after hrs of debugging😅), as suggested by Archith and have added the screenshots and the updated code also.

**Comment by archithdwij** [comment]
@kichloo The timer is set automatically right? Can we have as an user provided input so that that restriction timer can be set by themselves?

**Comment by kichloo** [comment]
> @kichloo The timer is set automatically right? Can we have as an user provided input so that that restriction timer can be set by themselves?

@archithdwij Yes, the user can set the time by himself also by changing the value in `start` and `end` like it is from 9 to 18 in this case

**Comment by kichloo** [comment]
I have added the functionality and updated README.md

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Hey @kichloo I tried your extension and as soon as I loaded the extension, it asked me for starting and ending time, I really don't get it, and then I looked for video and readme and there also it was not mentioned. 

- Update the video and readme regarding starting and ending time 
- In my case only site it blocked is Twitter that too when I accessed Twitter by searching twitter.com but when I used the shortcut or bookmark to open twitter then the extension is not able to block it and other socials are not blocked like I opened youtube and quora they were opening.

**Comment by kichloo** [comment]
> Hey @kichloo I tried your extension and as soon as I loaded the extension, it asked me for starting and ending time, I really don't get it, and then I looked for video and readme and there also it was not mentioned.
> 
> * Update the video and readme regarding starting and ending time
> * In my case only site it blocked is Twitter that too when I accessed Twitter by searching twitter.com but when I used the shortcut or bookmark to open twitter then the extension is not able to block it and other socials are not blocked like I opened youtube and quora they were opening.

@Nitesh-thapliyal In the above threads, Archit had asked for adding the functionality of timer, which could block sites from `start `to `end`. Those fields refer to that. In addition to that, regarding the blocking, I just read that generally, for applying changes, one needs to restart the system/ sometimes it works work without restarting.  So, would advice use you to do a system restart after enabling the extension. And I would update these in `README.md`

**Review by Nitesh-thapliyal — APPROVED** [review]

**Review by sudhanshutiwari264 — APPROVED** [review]
LGTM !

**Review by jainaayush01 — CHANGES_REQUESTED** [review]
What if I have to update the times?

Can you make the suggested changes before today evening(you have 5-6 hours)

**Comment by kichloo** [comment]
> What if I have to update the times?
> 
> Can you make the suggested changes before today evening(you have 5-6 hours)

You could simply reload the extension and enter the `starting` and `ending` or you could update the time by changing the `start` and `end` in background.js.

**Comment by sudhanshutiwari264** [comment]
@all-contributors Please add @imnishanth for code, design, infra

**Comment by sudhanshutiwari264** [comment]
@all-contributors Please add @kichloo  for code, design, infra

**Pull request merged**
