### PR TITLE
Meeting Notes 

### PR DESCRIPTION
**Pull request by imnishanth**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [x] Extension 
- [ ] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Hey @imnishanth  nice work 👏
As there are many note taking extensions already available in the market so, can you add extra features that will make your extension stand out from them,  Here is the list of the note taking extensions,  go through them, analyze their feature, functionality and make your extension more productive. [Note taking extensions](https://www.takenotesguide.com/most-helpful-chrome-extensions-for-taking-notes-13-tested/)

- I tried your extension and new note feature is not working as it overrides the older note,  it is not creating a new note and it gives the following error👇
Screenshot (1213)

**Review by Nitesh-thapliyal — APPROVED** [review]

**Review by sudhanshutiwari264 — APPROVED** [review]
Thanks for your dedication!

**Comment by sudhanshutiwari264** [comment]
@all-contributors Please add @imnishanth  for code,  design, infra

**Review by jainaayush01 — COMMENTED** [review]
Congratulations @imnishanth  for getting your PR merged 🥳

**Review by SulthanNK — COMMENTED** [review]
Congrats @imnishanth for getting your PR merged 🎉

**Pull request merged**
