### PR TITLE
Onestop-manager

### PR DESCRIPTION
**Pull request by bhushankelkar**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [x] Extension 
- [ ] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Hey @bhushankelkar great work👏

I tried your extension it works great⭐

Here are some suggestions that you can work on:

- Can you change the background color from the default white color
- Font style can be changed and align the text in the center for a better look and feel.

Screenshot (1176)

- Same goes for images, try to align the image in the center.

Screenshot (1177)

**Comment by bhushankelkar** [comment]
Thank you for the feedback. Will surely do that.

**Comment by bhushankelkar** [comment]
We have added the suggested changes. Do have a check!

**Comment by Nitesh-thapliyal** [comment]
> We have added the suggested changes. Do have a check!

Hey @bhushankelkar now the extension looks Great ⭐
but if possible can you align content in the center like the image below
sgNe9Av3R4

**Comment by bhushankelkar** [comment]
Fixed the text displayed

**Review by Nitesh-thapliyal — APPROVED** [review]

**Review by jainaayush01 — APPROVED** [review]

**Review by sudhanshutiwari264 — APPROVED** [review]
@bhushankelkar Great work :partying_face: 
I think it's good for folks like me :smile: 
thanks for your dedication.

**Comment by archithdwij** [comment]
@bhushankelkar  Kindly do not close your PR :)
Your project is at the verge of merging. Let us know before taking any actions.

**Comment by bhushankelkar** [comment]
Thanks a lot @Nitesh-thapliyal  @jainaayush01  @sudhanshutiwari264  for your valuable suggestions!

**Comment by bhushankelkar** [comment]
@archithdwij I'll reopen it.

**Review by archithdwij — APPROVED** [review]
@bhushankelkar I used your extension and it contains a bunch of fun activities. Yes or No is my favorite since that serves as a toss whenever I need to make decisions 😄 Kudos man! Congratulations on getting your PR merged 💯

**Comment by archithdwij** [comment]
@all-contributors Please add @bhushankelkar for code, design, infra, idea

**Comment by archithdwij** [comment]
@bhushankelkar Do not forget to submit your project demo video and blog in the submission form.

**Comment by bhushankelkar** [comment]
@archithdwij can you'll add @kamatvedita99 as contributor?

**Comment by sudhanshutiwari264** [comment]
@all-contributors Please add  @kamatvedita99 for code, design, infra, idea

**Comment by archithdwij** [comment]
@bhushankelkar Sure! Is there any specific part of the contribution she put more effort on? Just an information requirement so that we can add the contributions accordingly :)

**Comment by sudhanshutiwari264** [comment]
Make sure @kamatvedita99 has registered for the event, @bhushankelkar!

**Comment by bhushankelkar** [comment]
@archithdwij yes she helped me with the designing part of the extension (frontend). Infact many of the ideas from the fun section were put forward by her! 
@sudhanshutiwari264 yes sure!

**Pull request merged**
