### PR TITLE
Pascaline : Chrome-extensions

### PR DESCRIPTION
**Pull request by 0xRitesh**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [x] Extension 
- [ ] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Hey @wordssaysalot nice work 👏
but there are many calculator extensions that are available and too with more functionality and considering it for productivity then functionality matters lot than UI. 
So, can you add some extra feature that will make your calculator stand out from other extensions and makes it more productive.
Here are the calculator extensions go through them, see their functionality and analyze features that you can add to make your extension more productive. [Calculator Extensions](https://www.ilovefreesoftware.com/24/featured/5-free-calculator-extensions-apps-chrome.html)

**Comment by jainaayush01** [comment]
any updates @wordssaysalot?
The deadline is over...

**Comment by 0xRitesh** [comment]
Hello @jainaayush01 @Nitesh-thapliyal,
Thank you very much for taking the time to review my project. I was thinking about what features I might add to make it more productive, but the main goal of my project was to create a basic calculator with a pleasant user interface that allows you to perform basic calculations without having to switch tabs or programs in your browser. I suppose complicated calculations will set my Pascaline apart from others, but those features will be of limited utility since if you need a difficult calculation, you'll use a scientific calculator rather than a basic one, and the UI will become clumsy too, defeating the purpose. still, I have a plan to improve the user interface since I believe that aesthetic design is important.

**Comment by jainaayush01** [comment]
Just a suggestion to ponder upon, don't you think there are calculators with the Nice UI as well as having more features?

Still we will see if it's a good fit.

I will check with the team and let you know.

**Review by jainaayush01 — APPROVED** [review]

**Review by theAdityaNVS — APPROVED** [review]
Good work on UI and readme banner !!
👍

**Review by SulthanNK — APPROVED** [review]
Kudo's to your work🎉 @wordssaysalot

**Review by sudhanshutiwari264 — APPROVED** [review]
Nice work @wordssaysalot

**Review by archithdwij — APPROVED** [review]
@wordssaysalot Great work! Congratulations on getting your PR merged 😃

**Comment by archithdwij** [comment]
@all-contributors Please Add @wordssaysalot for code, infra, idea, idea

**Pull request merged**
